"""
SwingAdvisorBot — Module 1: Data Layer
fetchers/earnings_fetcher.py — NSE corporate earnings calendar fetcher

Earnings events are binary risk events. A stock can move ±8-15% on
result day, making swing position sizing impossible. Every setup
generated by M4 must be checked against this calendar before being
shown to Vijay.

Risk classification by days until result:
  ≤ 2 days → HIGH   → Block setup entirely. No entry.
  3-5 days → MEDIUM → Warn. Reduce confidence score by 2.
  6-10 days → LOW   → Note. Show advisory in setup card.
  > 10 days → NONE  → No action needed.

Data source:
  NSE corporate announcements API:
  https://www.nseindia.com/api/corporate-announcements
    ?index=equities&from_date=DD-MM-YYYY&to_date=DD-MM-YYYY

  Filters for: "Quarterly Results", "Financial Results", "Annual Results".
  Date range: today → today + 10 trading days.
  Requires NseSessionManager cookies (same as FII/DII fetcher).

Caching:
  TTL: 3,600 seconds (1 hour).
  Cache key: "earnings:{YYYY-MM-DD}" — one entry per day.
  Returns cached dict[ticker → EarningsEvent] for fast per-stock lookup.

Models defined here (re-exported by models.py in File 04):
  EarningsRiskLevel — HIGH / MEDIUM / LOW / NONE
  EarningsEvent     — Full earnings event with advisor warning
  EarningsRisk      — Compact risk summary attached to each setup card

Usage:
  from module1_data_layer.fetchers.earnings_fetcher import earnings_fetcher

  # Fetch all upcoming earnings for a list of tickers
  events = await earnings_fetcher.fetch_upcoming(["INFY", "TCS", "HDFCBANK"])

  # Check single ticker
  risk = await earnings_fetcher.check_ticker("INFY")
  if risk and risk.risk_level == EarningsRiskLevel.HIGH:
      # Block setup
"""

from __future__ import annotations

import enum
import gzip
import json as _json
import logging
from datetime import datetime, timedelta
from typing import Optional

import httpx
from pydantic import BaseModel, Field
from zoneinfo import ZoneInfo

from module1_data_layer.cache import cache
from module1_data_layer.config import STOCK_METADATA
from module1_data_layer.fetchers.nse_session_manager import nse_session

IST = ZoneInfo("Asia/Kolkata")

logger = logging.getLogger("swing_advisor.fetchers.earnings")

# NSE corporate announcements endpoint
NSE_ANNOUNCEMENTS_URL = (
    "https://www.nseindia.com/api/corporate-announcements"
)

# Look ahead window for earnings risk detection
EARNINGS_LOOK_AHEAD_DAYS: int = 10

# Cache TTL: 1 hour (earnings calendar rarely changes intraday)
CACHE_TTL_EARNINGS: int = 3_600

# Request timeout
_TIMEOUT_SEC: float = 15.0

# Keywords that identify earnings/results announcements
_RESULTS_KEYWORDS: frozenset[str] = frozenset({
    "quarterly results",
    "financial results",
    "annual results",
    "q1 results",
    "q2 results",
    "q3 results",
    "q4 results",
    "half yearly results",
    "unaudited results",
    "audited results",
})

# NSE date format (DD-MM-YYYY)
_NSE_DATE_FMT = "%d-%m-%Y"
# ISO date format used internally
_ISO_DATE_FMT = "%Y-%m-%d"


# ─────────────────────────────────────────────────────────────
# Enums and Models
# Defined here, re-exported by models.py in File 04.
# ─────────────────────────────────────────────────────────────


class EarningsRiskLevel(str, enum.Enum):
    """Risk level assigned to a stock based on days until earnings result.

    Rules:
      HIGH   → ≤ 2 days — binary event too close. Block all new setups.
      MEDIUM → 3-5 days — significant risk window. Warn + reduce confidence.
      LOW    → 6-10 days — on horizon. Note in setup card.
      NONE   → > 10 days — no near-term earnings risk.
    """

    HIGH = "HIGH"
    MEDIUM = "MEDIUM"
    LOW = "LOW"
    NONE = "NONE"


class EarningsEvent(BaseModel):
    """A single earnings result event for a listed NSE stock.

    Carries full advisor-quality context: days to result, risk level,
    advisor warning, and estimated historical price reaction.

    Used by:
      M4 stock_screener — block/warn/note candidate setups
      M6 morning_brief — "Earnings this week" section
      Frontend setup card — inline earnings risk badge
    """

    ticker: str = Field(..., description="NSE ticker symbol e.g. INFY")
    company_name: str = Field(
        ..., description="Full company name e.g. Infosys Limited"
    )
    result_date: str = Field(
        ..., description="Result announcement date YYYY-MM-DD"
    )
    days_to_result: int = Field(
        ...,
        description="Calendar days from today to result_date. "
                    "0 = today, 1 = tomorrow, etc.",
    )
    result_type: str = Field(
        default="quarterly",
        description="quarterly / annual / half_yearly",
    )
    quarter: str = Field(
        default="",
        description="Quarter label e.g. Q4 FY26. Empty if annual.",
    )
    risk_level: EarningsRiskLevel = Field(
        ..., description="HIGH / MEDIUM / LOW / NONE based on days_to_result"
    )
    advisor_warning: str = Field(
        ...,
        description="Human-readable warning shown on setup card and morning brief.",
    )
    historical_reaction: str = Field(
        default="",
        description="Average ±% move on result day from historical data. "
                    "Empty when data unavailable.",
    )


class EarningsRisk(BaseModel):
    """Compact earnings risk summary attached to each setup card.

    Embedded inside TradeSetup (M4 models) so the frontend and M6
    always have the risk context alongside the trade levels.

    Exactly 4 fields — M4 screener and M6 morning brief depend on this shape.
    """

    has_upcoming_earnings: bool = Field(
        default=False,
        description="True if stock has earnings in the next 10 days.",
    )
    days_to_result: Optional[int] = Field(
        default=None,
        description="Days until result. None if no upcoming earnings.",
    )
    risk_level: EarningsRiskLevel = Field(
        default=EarningsRiskLevel.NONE,
        description="HIGH/MEDIUM/LOW/NONE",
    )
    advisor_warning: Optional[str] = Field(
        default=None,
        description="Short warning shown on setup card. None if no earnings risk.",
    )


# ─────────────────────────────────────────────────────────────
# Fetcher
# ─────────────────────────────────────────────────────────────


class EarningsFetcher:
    """Fetches NSE corporate earnings calendar for upcoming results.

    Pipeline:
      1. Check cache (TTL 1 hour) → return if fresh
      2. Build date range: today → today + 10 days (NSE DD-MM-YYYY format)
      3. GET NSE corporate-announcements API with session cookies
      4. Filter announcements for results-type events only
      5. Build dict[ticker → EarningsEvent] with risk classification
      6. Store in cache → return

    On failure: returns empty dict (pipeline is not blocked by missing
    earnings data — setup generator shows NO_EARNINGS_DATA note).
    """

    async def fetch_upcoming(
        self,
        tickers: Optional[list[str]] = None,
        days_ahead: int = EARNINGS_LOOK_AHEAD_DAYS,
    ) -> dict[str, EarningsEvent]:
        """Fetch earnings events for the next `days_ahead` calendar days.

        Args:
            tickers: If provided, only return events for these tickers.
                     If None, returns all NSE earnings events found.
            days_ahead: How many days ahead to scan (default 10).

        Returns:
            Dict mapping ticker → EarningsEvent.
            Empty dict if NSE is unreachable.
        """
        today = datetime.now(IST).date()
        cache_key = f"earnings:{today.strftime(_ISO_DATE_FMT)}"

        # ── Step 1: Cache hit ──────────────────────────────────
        cached = cache.get(cache_key)
        if cached is not None:
            logger.debug(f"[Earnings] Cache hit for {today}")
            if tickers:
                tickers_upper = {t.upper() for t in tickers}
                return {k: v for k, v in cached.items() if k in tickers_upper}
            return cached

        # ── Steps 2–5: Fetch and build calendar ───────────────
        end_date = today + timedelta(days=days_ahead)
        raw = await self._call_nse_api(today, end_date)

        if raw is None:
            logger.warning("[Earnings] NSE announcements API unreachable.")
            return {}

        calendar = self._parse_announcements(raw, today)

        # ── Step 6: Cache full calendar ────────────────────────
        cache.set(cache_key, calendar, CACHE_TTL_EARNINGS)

        logger.info(
            f"[Earnings] {len(calendar)} upcoming results found "
            f"({today} → {end_date})"
        )

        if tickers:
            tickers_upper = {t.upper() for t in tickers}
            return {k: v for k, v in calendar.items() if k in tickers_upper}
        return calendar

    async def check_ticker(
        self,
        ticker: str,
        days_ahead: int = EARNINGS_LOOK_AHEAD_DAYS,
    ) -> Optional[EarningsEvent]:
        """Check a single ticker for upcoming earnings risk.

        Convenience wrapper around fetch_upcoming() for M4's per-stock check.

        Args:
            ticker: NSE ticker symbol e.g. "INFY".
            days_ahead: Look-ahead window.

        Returns:
            EarningsEvent if the stock has results within days_ahead, else None.
        """
        calendar = await self.fetch_upcoming(
            tickers=[ticker], days_ahead=days_ahead
        )
        return calendar.get(ticker.upper())

    def build_earnings_risk(
        self, event: Optional[EarningsEvent]
    ) -> EarningsRisk:
        """Convert an EarningsEvent (or None) into a compact EarningsRisk.

        Used by M4 stock_screener to attach risk to each setup card.

        Args:
            event: EarningsEvent if the stock has upcoming earnings, else None.

        Returns:
            EarningsRisk with has_upcoming_earnings=False if event is None.
        """
        if event is None:
            return EarningsRisk()

        return EarningsRisk(
            has_upcoming_earnings=True,
            days_to_result=event.days_to_result,
            risk_level=event.risk_level,
            advisor_warning=event.advisor_warning,
        )

    # ─────────────────────────────────────────────────────────
    # Private helpers
    # ─────────────────────────────────────────────────────────

    async def _call_nse_api(
        self, from_date: "date", to_date: "date"
    ) -> Optional[list[dict]]:
        """GET NSE corporate announcements with session cookies.

        Args:
            from_date: Start date for the query window.
            to_date:   End date for the query window.

        Returns:
            Parsed JSON list on success, None on failure.
        """
        params = {
            "index": "equities",
            "from_date": from_date.strftime(_NSE_DATE_FMT),
            "to_date": to_date.strftime(_NSE_DATE_FMT),
        }

        for attempt in range(2):
            headers, cookies = await nse_session.get_session_context()
            try:
                async with httpx.AsyncClient(
                    follow_redirects=True,
                    timeout=_TIMEOUT_SEC,
                ) as client:
                    resp = await client.get(
                        NSE_ANNOUNCEMENTS_URL,
                        params=params,
                        headers=headers,
                        cookies=cookies,
                    )

                    if resp.status_code in (401, 403):
                        logger.warning(
                            f"[Earnings] NSE returned {resp.status_code} "
                            f"(attempt {attempt + 1}) — invalidating session."
                        )
                        nse_session.invalidate()
                        continue

                    resp.raise_for_status()

                    # NSE sends gzip-compressed JSON when Accept-Encoding is
                    # passed manually. Decompress if resp.json() fails.
                    try:
                        data = resp.json()
                    except (ValueError, UnicodeDecodeError):
                        try:
                            raw = gzip.decompress(resp.content)
                            data = _json.loads(raw)
                        except Exception as decomp_err:
                            logger.warning(
                                f"[Earnings] Failed to decode NSE response: {decomp_err}"
                            )
                            return None

                    if isinstance(data, list):
                        return data
                    # Some NSE endpoints wrap in {"data": [...]}
                    if isinstance(data, dict) and "data" in data:
                        return data["data"]

                    logger.warning(
                        f"[Earnings] Unexpected response type: "
                        f"{type(data).__name__}"
                    )
                    return None

            except httpx.TimeoutException:
                logger.warning(
                    f"[Earnings] NSE API timed out (attempt {attempt + 1})."
                )
            except httpx.HTTPStatusError as exc:
                logger.warning(
                    f"[Earnings] NSE HTTP error {exc.response.status_code}"
                )
                return None
            except Exception as exc:
                logger.warning(f"[Earnings] Unexpected error: {exc}")
                return None

        return None

    def _parse_announcements(
        self,
        data: list[dict],
        today: "date",
    ) -> dict[str, EarningsEvent]:
        """Parse NSE corporate announcements into a ticker → EarningsEvent map.

        Filters to results-type announcements only.
        Deduplicates: keeps the nearest result date per ticker.

        NSE announcement object shape (typical):
          {
            "symbol":   "INFY",
            "series":   "EQ",
            "subject":  "Financial Results for the quarter ended March 2026",
            "bm_desc":  "Board Meeting",
            "date":     "22-May-2026",       # board meeting date
            "recDate":  "",
            "purpose":  "Quarterly Results"  # can also be in subject
          }

        Note: NSE sometimes uses "date" in "22-May-2026" format,
        other times "bm_date" in "2026-05-22" format.
        Both are handled below.

        Returns:
            dict[ticker → EarningsEvent] with nearest result per ticker.
        """
        calendar: dict[str, EarningsEvent] = {}

        for item in data:
            # ── Extract ticker ─────────────────────────────────
            ticker = (
                str(item.get("symbol") or item.get("scrip_cd") or "")
                .upper()
                .strip()
            )
            if not ticker:
                continue

            # ── Check if this is a results announcement ────────
            subject = str(item.get("subject") or item.get("desc") or "").lower()
            purpose = str(item.get("purpose") or item.get("bm_desc") or "").lower()
            combined_text = f"{subject} {purpose}"

            if not _is_results_announcement(combined_text):
                continue

            # ── Parse announcement date ────────────────────────
            result_date = _parse_nse_date(
                item.get("date") or item.get("bm_date") or ""
            )
            if result_date is None:
                continue

            # Must be on or after today
            if result_date < today:
                continue

            days_to_result = (result_date - today).days

            # ── Deduplicate: keep nearest result date ──────────
            if ticker in calendar:
                existing = calendar[ticker]
                if days_to_result >= existing.days_to_result:
                    continue  # Keep the closer one

            # ── Classify risk ──────────────────────────────────
            risk_level = classify_earnings_risk(days_to_result)

            # ── Determine result type + quarter ───────────────
            result_type, quarter = _infer_result_type(combined_text)

            # ── Company name from STOCK_METADATA ──────────────
            company_name = STOCK_METADATA.get(ticker, {}).get(
                "company_name", ticker
            )

            # ── Advisor warning ────────────────────────────────
            advisor_warning = _build_advisor_warning(
                ticker=ticker,
                company_name=company_name,
                days_to_result=days_to_result,
                result_date_str=result_date.strftime("%a %d %b"),
                risk_level=risk_level,
            )

            calendar[ticker] = EarningsEvent(
                ticker=ticker,
                company_name=company_name,
                result_date=result_date.strftime(_ISO_DATE_FMT),
                days_to_result=days_to_result,
                result_type=result_type,
                quarter=quarter,
                risk_level=risk_level,
                advisor_warning=advisor_warning,
            )

        return calendar


# ─────────────────────────────────────────────────────────────
# Pure helper functions — easy to unit-test in isolation
# ─────────────────────────────────────────────────────────────


def classify_earnings_risk(days_to_result: int) -> EarningsRiskLevel:
    """Classify earnings risk based on calendar days until result.

    Args:
        days_to_result: 0 = today, 1 = tomorrow, etc.

    Returns:
        EarningsRiskLevel enum value.

    Examples:
        >>> classify_earnings_risk(1)
        EarningsRiskLevel.HIGH
        >>> classify_earnings_risk(4)
        EarningsRiskLevel.MEDIUM
        >>> classify_earnings_risk(8)
        EarningsRiskLevel.LOW
        >>> classify_earnings_risk(15)
        EarningsRiskLevel.NONE
    """
    if days_to_result <= 2:
        return EarningsRiskLevel.HIGH
    elif days_to_result <= 5:
        return EarningsRiskLevel.MEDIUM
    elif days_to_result <= 10:
        return EarningsRiskLevel.LOW
    else:
        return EarningsRiskLevel.NONE


def _is_results_announcement(text: str) -> bool:
    """Return True if the announcement text indicates an earnings result event."""
    return any(keyword in text for keyword in _RESULTS_KEYWORDS)


def _parse_nse_date(date_str: str) -> Optional["date"]:
    """Parse an NSE date string into a Python date.

    NSE uses multiple formats:
      "22-May-2026"  → strptime("%d-%b-%Y")
      "2026-05-22"   → strptime("%Y-%m-%d")
      "22-05-2026"   → strptime("%d-%m-%Y")
    """
    date_str = str(date_str).strip()
    if not date_str:
        return None

    for fmt in ("%d-%b-%Y", "%Y-%m-%d", "%d-%m-%Y", "%d/%m/%Y"):
        try:
            return datetime.strptime(date_str, fmt).date()
        except ValueError:
            continue

    logger.debug(f"[Earnings] Could not parse date: '{date_str}'")
    return None


def _infer_result_type(text: str) -> tuple[str, str]:
    """Infer result type and quarter label from announcement text.

    Returns:
        (result_type, quarter_label)
        e.g. ("quarterly", "Q4 FY26") or ("annual", "FY26")
    """
    text = text.lower()

    # Detect fiscal year from text (e.g. "fy 2026", "fy26", "2025-26")
    import re
    fy_match = re.search(r"(?:fy\s?(\d{2,4})|(\d{4})-(\d{2}))", text)
    fy_label = ""
    if fy_match:
        if fy_match.group(1):
            yr = fy_match.group(1)
            fy_label = f"FY{yr[-2:]}" if len(yr) == 4 else f"FY{yr}"
        elif fy_match.group(2):
            fy_label = f"FY{fy_match.group(3)}"

    if "annual" in text or "year ended" in text or "full year" in text:
        return "annual", fy_label or "FY26"

    if "half" in text or "h1" in text or "h2" in text:
        half = "H1" if "h1" in text else "H2"
        return "half_yearly", f"{half} {fy_label}" if fy_label else half

    # Quarterly — detect Q1/Q2/Q3/Q4
    q_match = re.search(r"q([1-4])", text)
    if q_match:
        q_num = q_match.group(1)
        return "quarterly", f"Q{q_num} {fy_label}" if fy_label else f"Q{q_num}"

    # Infer quarter from month mentions
    month_to_quarter = {
        "june": "Q1", "jul": "Q1",
        "september": "Q2", "sep": "Q2",
        "december": "Q3", "dec": "Q3",
        "march": "Q4", "mar": "Q4",
    }
    for month, quarter in month_to_quarter.items():
        if month in text:
            return "quarterly", f"{quarter} {fy_label}" if fy_label else quarter

    return "quarterly", f"Q4 {fy_label}" if fy_label else "Q4 FY26"


def _build_advisor_warning(
    ticker: str,
    company_name: str,
    days_to_result: int,
    result_date_str: str,
    risk_level: EarningsRiskLevel,
) -> str:
    """Build a concise, actionable advisor warning for a setup card.

    Args:
        ticker: NSE ticker e.g. "INFY"
        company_name: Full name e.g. "Infosys Limited"
        days_to_result: Calendar days until result
        result_date_str: Human-readable date e.g. "Thu 22 May"
        risk_level: Classified risk level

    Returns:
        1-2 sentence warning string with concrete guidance.
    """
    day_word = "today" if days_to_result == 0 else (
        "tomorrow" if days_to_result == 1 else f"in {days_to_result} days"
    )

    if risk_level == EarningsRiskLevel.HIGH:
        return (
            f"{ticker} reports results {day_word} ({result_date_str}). "
            f"Do NOT enter any new swing position — results create binary "
            f"risk that invalidates all technical levels. "
            f"This setup is BLOCKED until post-result stability."
        )
    elif risk_level == EarningsRiskLevel.MEDIUM:
        return (
            f"{ticker} reports results {day_word} ({result_date_str}). "
            f"Significant earnings risk — a 5-10% gap is possible on result day. "
            f"If entering, use a hard stop and consider exiting before results."
        )
    else:  # LOW
        return (
            f"{ticker} results due {result_date_str} ({days_to_result} days). "
            f"Monitor the position — plan your exit before result week begins."
        )


# ─────────────────────────────────────────────────────────────
# Module-level singleton
# ─────────────────────────────────────────────────────────────

earnings_fetcher: EarningsFetcher = EarningsFetcher()
"""Shared earnings fetcher singleton.

Usage:
    from module1_data_layer.fetchers.earnings_fetcher import earnings_fetcher

    events = await earnings_fetcher.fetch_upcoming(["INFY", "TCS"])
    for ticker, event in events.items():
        print(ticker, event.risk_level, event.advisor_warning)
"""
