"""Module 7 — Education Layer models."""

from __future__ import annotations

import enum
from datetime import datetime
from typing import Optional

from pydantic import BaseModel, computed_field


# ── Enums ────────────────────────────────────────────────────

class DifficultyLevel(str, enum.Enum):
    BEGINNER = "beginner"
    BEGINNER_PLUS = "beginner+"
    INTERMEDIATE = "intermediate"
    INTERMEDIATE_PLUS = "intermediate+"


# ── Sub-models ───────────────────────────────────────────────

class ConceptTrigger(BaseModel):
    """Maps an advisor flag / market signal to teachable concepts."""
    trigger: str  # e.g. "unusual_activity", "vix_high"
    concepts: list[str]  # ordered by priority


class RealExample(BaseModel):
    """Today's market data anchoring the lesson."""
    ticker: Optional[str] = None
    event: str  # e.g. "price +2.66% on 1.14x avg volume"
    signal: Optional[str] = None  # e.g. "institutional_accumulation"
    impact: Optional[str] = None  # e.g. "No new swing trades today"


class Quiz(BaseModel):
    """One A/B quiz question tied to the lesson."""
    question: str
    options: dict[str, str]  # {"A": "...", "B": "..."}
    correct: str  # "A" or "B"
    explanation: str


class Lesson(BaseModel):
    """Full lesson generated by M7 — stored in M5, sent via M6."""
    lesson_id: str  # e.g. "L-20260515-volume_analysis"
    concept: str  # key into CONCEPT_LIBRARY
    title: str  # displayed in Telegram
    difficulty: DifficultyLevel = DifficultyLevel.BEGINNER
    market_trigger: str  # what today's data triggered this lesson
    real_example: RealExample
    lesson_text: str  # 3-4 sentences, plain English
    key_takeaway: str  # one actionable sentence
    quiz: Quiz
    tokens_used: int = 0
    generated_at: datetime
    is_fallback: bool = False  # True if from CONCEPT_LIBRARY

    def to_brief(self) -> LessonBrief:
        """Trim to ≤200-token version for M6 morning brief."""
        return LessonBrief(
            lesson_id=self.lesson_id,
            concept=self.concept,
            title=self.title,
            difficulty=self.difficulty.value,
            summary=self.key_takeaway,
            quiz_question=self.quiz.question,
            quiz_options=self.quiz.options,
        )


class LessonBrief(BaseModel):
    """Compact lesson payload embedded in M6 MorningBrief."""
    lesson_id: str
    concept: str
    title: str
    difficulty: str = "beginner"
    summary: str  # key_takeaway from full lesson
    quiz_question: str
    quiz_options: dict[str, str]


# ── Quiz response / feedback ─────────────────────────────────

class QuizResponse(BaseModel):
    """Incoming quiz answer from Telegram."""
    user_id: str = "XCU700"
    lesson_id: str
    answer: str  # "A" or "B"


class QuizFeedback(BaseModel):
    """Feedback sent back after quiz submission."""
    correct: bool
    feedback_html: str  # HTML for Telegram
    new_score: Optional[int] = None  # weekly score %
    streak: int = 0  # consecutive correct answers


# ── Learning progress (extends M5 view) ──────────────────────

class WeeklyScore(BaseModel):
    """Aggregated quiz performance for one week."""
    week_start: str  # YYYY-MM-DD (Monday)
    total_quizzes: int = 0
    correct_answers: int = 0

    @computed_field
    @property
    def score_pct(self) -> float:
        if self.total_quizzes == 0:
            return 0.0
        return round(self.correct_answers / self.total_quizzes * 100, 1)


class LearningSnapshot(BaseModel):
    """Current learning state for difficulty adaptation."""
    user_id: str = "XCU700"
    current_difficulty: DifficultyLevel = DifficultyLevel.BEGINNER
    concepts_taught_this_week: list[str] = []
    total_concepts_taught: int = 0
    recent_weeks: list[WeeklyScore] = []  # last 4 weeks
    current_streak: int = 0  # consecutive correct

    @computed_field
    @property
    def should_upgrade(self) -> bool:
        """Score ≥80% for 2 consecutive weeks → upgrade."""
        if len(self.recent_weeks) < 2:
            return False
        return all(w.score_pct >= 80.0 for w in self.recent_weeks[:2])

    @computed_field
    @property
    def should_downgrade(self) -> bool:
        """Score <60% for 1 week → downgrade."""
        if len(self.recent_weeks) < 1:
            return False
        return self.recent_weeks[0].score_pct < 60.0


# ── Concept definition (from config library) ─────────────────

class ConceptDefinition(BaseModel):
    """Pre-built concept from CONCEPT_LIBRARY."""
    concept: str
    definition: str
    triggers: list[str]
    difficulty: DifficultyLevel
    fallback_lesson: str  # used when Claude unavailable
    fallback_quiz_question: str
    fallback_quiz_options: dict[str, str]  # {"A": "...", "B": "..."}
    fallback_quiz_correct: str  # "A" or "B"
    fallback_quiz_explanation: str
